<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE errori [
  <!ELEMENT errori (id_fornitura, data_invio, num_conti_ok, errore*)>
  <!ELEMENT id_fornitura (#PCDATA)>
  <!ELEMENT data_invio (#PCDATA)>
  <!ELEMENT num_conti_ok (#PCDATA)>
  <!ELEMENT errore (prog, code, descr?, type?, output?)>
  <!ELEMENT prog (#PCDATA)>
  <!ELEMENT code (#PCDATA)>
  <!ELEMENT descr (#PCDATA)>
  <!ELEMENT type (#PCDATA)>
  <!ELEMENT output (#PCDATA)>
]>
<errori>
  <id_fornitura>64</id_fornitura>
  <data_invio>2011-10-24</data_invio>
  <num_conti_ok>7</num_conti_ok>
  <errore>
    <prog>4085</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
</errori>
