<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE errori [
  <!ELEMENT errori (id_fornitura, data_invio, num_conti_ok, errore*)>
  <!ELEMENT id_fornitura (#PCDATA)>
  <!ELEMENT data_invio (#PCDATA)>
  <!ELEMENT num_conti_ok (#PCDATA)>
  <!ELEMENT errore (prog, code, descr?, type?, output?)>
  <!ELEMENT prog (#PCDATA)>
  <!ELEMENT code (#PCDATA)>
  <!ELEMENT descr (#PCDATA)>
  <!ELEMENT type (#PCDATA)>
  <!ELEMENT output (#PCDATA)>
]>
<errori>
  <id_fornitura>46</id_fornitura>
  <data_invio>2011-07-13</data_invio>
  <num_conti_ok>111</num_conti_ok>
  <errore>
    <prog>4816</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>5581</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>12272</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>16356</prog>
    <code>XX13</code>
    <descr>DATI INCONGRUENTI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>17537</prog>
    <code>XX10</code>
    <descr>IL CODICE FISCALE INSERITO E' UN COLLEGATO</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>22016</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>32133</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>41455</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>41579</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>56600</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>68850</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>85519</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>96759</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>115266</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>116208</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>123791</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>126117</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>129320</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>147519</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>159542</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>161227</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>162657</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>164057</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>167491</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>168205</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>168447</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>169579</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>170519</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>170941</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>171639</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>172892</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>173159</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>174039</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>175055</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>175067</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
</errori>
