<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE errori [
  <!ELEMENT errori (id_fornitura, data_invio, num_conti_ok, errore*)>
  <!ELEMENT id_fornitura (#PCDATA)>
  <!ELEMENT data_invio (#PCDATA)>
  <!ELEMENT num_conti_ok (#PCDATA)>
  <!ELEMENT errore (prog, code, descr?, type?, output?)>
  <!ELEMENT prog (#PCDATA)>
  <!ELEMENT code (#PCDATA)>
  <!ELEMENT descr (#PCDATA)>
  <!ELEMENT type (#PCDATA)>
  <!ELEMENT output (#PCDATA)>
]>
<errori>
  <id_fornitura>39</id_fornitura>
  <data_invio>2011-07-05</data_invio>
  <num_conti_ok>163</num_conti_ok>
  <errore>
    <prog>80530</prog>
    <code>-10</code>
    <descr>ERRORE FORMALE DEL RECORD (FORMATTAZIONE DELLA DATA, CAMPI, ECC.)</descr>
    <type>ERROR</type>
    <output><![CDATA[Caratteri non ammessi in comune_nascita]]></output>
  </errore>
  <errore>
    <prog>80942</prog>
    <code>-10</code>
    <descr>ERRORE FORMALE DEL RECORD (FORMATTAZIONE DELLA DATA, CAMPI, ECC.)</descr>
    <type>ERROR</type>
    <output><![CDATA[Caratteri non ammessi in comune_nascita]]></output>
  </errore>
  <errore>
    <prog>81369</prog>
    <code>-10</code>
    <descr>ERRORE FORMALE DEL RECORD (FORMATTAZIONE DELLA DATA, CAMPI, ECC.)</descr>
    <type>ERROR</type>
    <output><![CDATA[Caratteri non ammessi in comune_nascita]]></output>
  </errore>
  <errore>
    <prog>81383</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>81749</prog>
    <code>-10</code>
    <descr>ERRORE FORMALE DEL RECORD (FORMATTAZIONE DELLA DATA, CAMPI, ECC.)</descr>
    <type>ERROR</type>
    <output><![CDATA[Caratteri non ammessi in comune_nascita]]></output>
  </errore>
  <errore>
    <prog>84224</prog>
    <code>-10</code>
    <descr>ERRORE FORMALE DEL RECORD (FORMATTAZIONE DELLA DATA, CAMPI, ECC.)</descr>
    <type>ERROR</type>
    <output><![CDATA[Caratteri non ammessi in comune_nascita]]></output>
  </errore>
  <errore>
    <prog>85759</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>86925</prog>
    <code>-10</code>
    <descr>ERRORE FORMALE DEL RECORD (FORMATTAZIONE DELLA DATA, CAMPI, ECC.)</descr>
    <type>ERROR</type>
    <output><![CDATA[Caratteri non ammessi in comune_nascita]]></output>
  </errore>
  <errore>
    <prog>86986</prog>
    <code>-10</code>
    <descr>ERRORE FORMALE DEL RECORD (FORMATTAZIONE DELLA DATA, CAMPI, ECC.)</descr>
    <type>ERROR</type>
    <output><![CDATA[Caratteri non ammessi in comune_nascita]]></output>
  </errore>
  <errore>
    <prog>88676</prog>
    <code>-10</code>
    <descr>ERRORE FORMALE DEL RECORD (FORMATTAZIONE DELLA DATA, CAMPI, ECC.)</descr>
    <type>ERROR</type>
    <output><![CDATA[Caratteri non ammessi in comune_nascita]]></output>
  </errore>
  <errore>
    <prog>89123</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>91682</prog>
    <code>-10</code>
    <descr>ERRORE FORMALE DEL RECORD (FORMATTAZIONE DELLA DATA, CAMPI, ECC.)</descr>
    <type>ERROR</type>
    <output><![CDATA[Caratteri non ammessi in comune_nascita]]></output>
  </errore>
  <errore>
    <prog>92935</prog>
    <code>-10</code>
    <descr>ERRORE FORMALE DEL RECORD (FORMATTAZIONE DELLA DATA, CAMPI, ECC.)</descr>
    <type>ERROR</type>
    <output><![CDATA[Caratteri non ammessi in comune_nascita]]></output>
  </errore>
  <errore>
    <prog>93496</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>93725</prog>
    <code>-10</code>
    <descr>ERRORE FORMALE DEL RECORD (FORMATTAZIONE DELLA DATA, CAMPI, ECC.)</descr>
    <type>ERROR</type>
    <output><![CDATA[Caratteri non ammessi in comune_nascita]]></output>
  </errore>
  <errore>
    <prog>94884</prog>
    <code>-10</code>
    <descr>ERRORE FORMALE DEL RECORD (FORMATTAZIONE DELLA DATA, CAMPI, ECC.)</descr>
    <type>ERROR</type>
    <output><![CDATA[Caratteri non ammessi in comune_nascita]]></output>
  </errore>
  <errore>
    <prog>95795</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>95958</prog>
    <code>-10</code>
    <descr>ERRORE FORMALE DEL RECORD (FORMATTAZIONE DELLA DATA, CAMPI, ECC.)</descr>
    <type>ERROR</type>
    <output><![CDATA[Caratteri non ammessi in comune_nascita]]></output>
  </errore>
  <errore>
    <prog>96519</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>96825</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>97704</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>98491</prog>
    <code>-10</code>
    <descr>ERRORE FORMALE DEL RECORD (FORMATTAZIONE DELLA DATA, CAMPI, ECC.)</descr>
    <type>ERROR</type>
    <output><![CDATA[Caratteri non ammessi in comune_nascita]]></output>
  </errore>
  <errore>
    <prog>101163</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>101269</prog>
    <code>-10</code>
    <descr>ERRORE FORMALE DEL RECORD (FORMATTAZIONE DELLA DATA, CAMPI, ECC.)</descr>
    <type>ERROR</type>
    <output><![CDATA[Caratteri non ammessi in comune_nascita]]></output>
  </errore>
  <errore>
    <prog>102624</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>102899</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>103187</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>104720</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>105420</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>105744</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>108511</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>108837</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>108968</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>110167</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>111551</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>111718</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>114584</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
</errori>
