<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE errori [
  <!ELEMENT errori (id_fornitura, data_invio, num_conti_ok, errore*)>
  <!ELEMENT id_fornitura (#PCDATA)>
  <!ELEMENT data_invio (#PCDATA)>
  <!ELEMENT num_conti_ok (#PCDATA)>
  <!ELEMENT errore (prog, code, descr?, type?, output?)>
  <!ELEMENT prog (#PCDATA)>
  <!ELEMENT code (#PCDATA)>
  <!ELEMENT descr (#PCDATA)>
  <!ELEMENT type (#PCDATA)>
  <!ELEMENT output (#PCDATA)>
]>
<errori>
  <id_fornitura>40</id_fornitura>
  <data_invio>2011-07-05</data_invio>
  <num_conti_ok>183</num_conti_ok>
  <errore>
    <prog>144989</prog>
    <code>XX00</code>
    <descr>PERSONA FISICA DECEDUTA</descr>
    <type>WARNING</type>
    
  </errore>
  <errore>
    <prog>116117</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>117097</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>117604</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>121204</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>121335</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>127580</prog>
    <code>XX10</code>
    <descr>IL CODICE FISCALE INSERITO E' UN COLLEGATO</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>127759</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>129130</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>130965</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>131016</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>134301</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>134561</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>135384</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>139521</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>143202</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
  <errore>
    <prog>154882</prog>
    <code>XX01</code>
    <descr>NON TROVATO ALCUN SOGGETTO CORRISPONDENTE AI DATI</descr>
    <type>ERROR</type>
    
  </errore>
</errori>
