<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE errori [
  <!ELEMENT errori (id_fornitura, data_invio, num_conti_ok, errore*)>
  <!ELEMENT id_fornitura (#PCDATA)>
  <!ELEMENT data_invio (#PCDATA)>
  <!ELEMENT num_conti_ok (#PCDATA)>
  <!ELEMENT errore (prog, code, descr?, type?, output?)>
  <!ELEMENT prog (#PCDATA)>
  <!ELEMENT code (#PCDATA)>
  <!ELEMENT descr (#PCDATA)>
  <!ELEMENT type (#PCDATA)>
  <!ELEMENT output (#PCDATA)>
]>
<errori>
  <id_fornitura>79</id_fornitura>
  <data_invio>2012-04-11</data_invio>
  <num_conti_ok>0</num_conti_ok>
  <errore>
    <prog>32580</prog>
    <code>XX10</code>
    <descr>IL CODICE FISCALE INSERITO E' UN COLLEGATO</descr>
    <type>ERROR</type>
    
  </errore>
</errori>
